# .github/workflows/main.yml

name: Trigger Netlify Build
on:
  schedule:
    # Run at 0215 daily
    - cron: '15 2 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
